services:
  database:
    image: 'postgres:latest'
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: rozklad_user
      POSTGRES_PASSWORD: IEALdiauSyFWXzPN
      POSTGRES_DB: rozklad_jazdy
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

volumes:
  pgdata:
